version: '3.7'
services:
  serverless:
    build:
      context: . 
      args: 
        - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
        - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
    tty: true
    working_dir: /src
    volumes:
      - ./src:/src
    env_file:
      - .env
