service: serverless-codepipeline

provider:
  name: aws
  runtime: nodejs16.x
  region: ap-northeast-1
  stage: dev
  iamRoleStatements:
    - Effect: Allow
      Action:
        - codepipeline:StartPipelineExecution
      Resource:
        - "arn:aws:codepipeline:*"
  usagePlan:
    quota:
      limit: 100
      offset: 2
      period: MONTH

functions:
  
  execute:
    handler: handler.execute
    environment:
      TOKEN: ${env:TOKEN}
      USER_ID_LIST:  ${env:USER_ID_LIST}
    events:
      - http:
          path: /
          method: post
          cors: true
          private: false
